"""fix customer unique constraint

Revision ID: 064c7580c8b9
Revises: 2327c6344508
Create Date: 2026-06-21 12:00:02.919153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '064c7580c8b9'
down_revision: Union[str, Sequence[str], None] = '2327c6344508'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customers', 'address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_unique_constraint('uq_customers_vat_number', 'customers', ['vat_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_customers_vat_number', 'customers', type_='unique')
    op.alter_column('customers', 'address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
