"""change order number format

Revision ID: 199810e55f3a
Revises: c633476941d7
Create Date: 2026-06-22 10:30:53.968120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '199810e55f3a'
down_revision: Union[str, Sequence[str], None] = 'c633476941d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'ck_positive_order_number',
        'orders',
        type_='check'
    )
    op.alter_column('orders', 'order_number',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=12),
               existing_nullable=False)
    op.create_check_constraint(
    'ck_order_number_format',
    'orders',
    r"order_number ~ '^[0-9]{4}-[0-9]{5}$'"
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'ck_order_number_format',
        'orders',
        type_='check'
    )

    op.alter_column('orders', 'order_number',
               existing_type=sa.String(length=12),
               type_=sa.INTEGER(),
               existing_nullable=False)
    
    op.create_check_constraint(
        'ck_positive_order_number',
        'orders',
        'order_number > 0'
    )
    # ### end Alembic commands ###
