"""fix: change current stock to decimal

Revision ID: 5457e8cf3dfd
Revises: 064c7580c8b9
Create Date: 2026-06-21 19:28:25.980037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5457e8cf3dfd'
down_revision: Union[str, Sequence[str], None] = '064c7580c8b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'current_stock',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=10, scale=3),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'current_stock',
               existing_type=sa.Numeric(precision=10, scale=3),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
