"""init database

Revision ID: f3f5e6d72f6a
Revises: 
Create Date: 2026-06-20 00:26:12.011953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3f5e6d72f6a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('name', sa.String(length=75), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('customers',
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('name', sa.String(length=75), nullable=False),
    sa.Column('vat_number', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('customer_number', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_number')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('order_number', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'CONFIRMED', 'DELIVERED', 'INVOICED', 'CANCELLED', name='order_status_enum', create_constraint=True), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.CheckConstraint('order_number > 0', name='ck_positive_order_number'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_number')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('sku', sa.String(length=12), nullable=False),
    sa.Column('name', sa.String(length=75), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('unit_price_ex_vat', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('vat_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('current_stock', sa.Integer(), nullable=False),
    sa.CheckConstraint("sku ~ '^[A-Z]{6}-[0-9]{5}$'", name='ck_valid_sku'),
    sa.CheckConstraint('current_stock >= 0', name='ck_non_negative_stock'),
    sa.CheckConstraint('unit_price_ex_vat >= 0', name='ck_positive_price'),
    sa.CheckConstraint('vat_rate >= 0 AND vat_rate <= 1', name='ck_product_vat_rate'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('invoice_number', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ISSUED', 'PAID', 'CANCELLED', name='invoice_status_enum', create_constraint=True), nullable=False),
    sa.CheckConstraint('invoice_number > 0', name='ck_positive_invoice_number'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number'),
    sa.UniqueConstraint('order_id')
    )
    op.create_table('order_lines',
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('vat_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_positive_quantity'),
    sa.CheckConstraint('unit_price >= 0', name='ck_positive_price'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_movements',
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('movement_type', sa.Enum('INBOUND', 'OUTBOUND', 'ADJUSTMENT', name='movement_type_enum', create_constraint=True), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoice_lines',
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('vat_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_positive_quantity'),
    sa.CheckConstraint('unit_price >= 0', name='ck_positive_price'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoice_lines')
    op.drop_table('stock_movements')
    op.drop_table('order_lines')
    op.drop_table('invoices')
    op.drop_table('products')
    op.drop_table('orders')
    op.drop_table('customers')
    op.drop_table('categories')
    # ### end Alembic commands ###
